// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqzohnkodceksbtjeuza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxem9obmtvZGNla3NidGpldXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTY1MzEsImV4cCI6MjA2MTY5MjUzMX0.1OBPGK_7q78qFW4QrPS9pQFA08RDFItFfPcP7vCYFqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);